### ISSUE TITLE
d package - different versions on same dependency

### ISSUE THREAD

**Issue by yonida** [medikoo/es6-set#7]
In `package.json` you have a dependency for `"d": "~0.1.1"`
There is also a dependency for `"es6-iterator": "2"`
`"es6-iterator"` has a dependency for `"d"` as well, but as `"d": "1"`
This causes `"d"` to be added twice in the bundle.
Can you use the same `"d"` version for both modules?

**Comment by medikoo** [comment]
Sure, published as v0.1.5

**Comment by yonida** [comment]
Thanks @medikoo !
